[[sources]]
type = "winit"

[sources.bindings]
direction-up = ["W"]
direction-down = ["S"]
direction-left = ["A"]
direction-right = ["D"]
jump = ["Space"]

[[filters]]
type = "dpad"
targets = ["direction"]
