[package]
name = "enact-winit"
version = "0.1.0"
edition = "2024"

[dependencies]
enact = { version = "0.1.0", path = "../enact" }
mint = "0.5.9"
winit = { version = "0.30.12", default-features = false, features = ["x11"] }
